//GET http://localhost:5000/api/orders/myorders
//GET http://localhost:5000/api/orders
GET http://localhost:3000/api/portfolios
# GET http://localhost:5000/api/customers
# GET http://localhost:5000/api/stock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0YWxoYXphaGlkNzEwQGdtYWlsLmNvbSIsImlhdCI6MTc1NDk5NTMwOSwiZXhwIjoxNzU1MDAyNTA5fQ.UltD8Y0st8s6XHnkUtCtMSVk1Rh0WDYO3d8zoE9Kqt4